# Generated by Django 3.2.6 on 2021-10-24 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categoria_estado_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='estado_c',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='um',
        ),
    ]
