# Generated by Django 3.2.6 on 2021-10-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadet',
            name='precio',
            field=models.FloatField(default=0, null=True),
        ),
    ]
