# Generated by Django 3.2.9 on 2021-11-15 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0007_auto_20211028_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenfacturaenc',
            name='cliente',
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenfacturaenc',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenfacturaenc',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('apertura', models.BigIntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sub_total', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cajas',
            },
        ),
    ]
