# Generated by Django 3.2.5 on 2021-11-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_auto_20211115_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='fecha_fin_timbrado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='fecha_ini_timbrado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='no_factura',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='no_timbrado',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
