# Generated by Django 3.2.9 on 2021-11-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_auto_20211115_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='apertura',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='caja',
            old_name='sub_total',
            new_name='entrada',
        ),
        migrations.RenameField(
            model_name='caja',
            old_name='total',
            new_name='saldo_actual',
        ),
        migrations.AddField(
            model_name='caja',
            name='salida',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
