# Generated by Django 3.2.9 on 2021-11-21 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0013_auto_20211120_1939'),
        ('ventas', '0010_auto_20211121_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.comprasenc'),
        ),
        migrations.AddField(
            model_name='caja',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.facturaenc'),
        ),
    ]
