# Generated by Django 3.2.9 on 2021-11-21 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0013_auto_20211120_1939'),
        ('ventas', '0012_auto_20211121_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.comprasdet'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.facturadet'),
        ),
    ]
