# Generated by Django 3.2.9 on 2021-11-21 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_auto_20211121_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='factura',
        ),
        migrations.AddField(
            model_name='facturadet',
            name='caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.caja'),
        ),
    ]
