# Generated by Django 3.2.9 on 2021-11-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_auto_20211121_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturadet',
            name='caja',
        ),
    ]
