# Generated by Django 3.2.9 on 2021-11-22 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0013_auto_20211120_1939'),
        ('ventas', '0016_caja_fac'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='comp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.comprasenc'),
        ),
    ]
