# Generated by Django 3.2.5 on 2021-11-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_auto_20211122_1816'),
        ('ventas', '0017_caja_comp'),
    ]

    operations = [
    ]
