# Generated by Django 3.2.9 on 2021-11-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_merge_0009_auto_20211122_1816_0017_caja_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaenc',
            name='no_factura',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
