# Generated by Django 3.2.9 on 2021-11-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_alter_facturaenc_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaenc',
            name='no_factura',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
