# Generated by Django 3.2.5 on 2021-11-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0027_alter_facturaenc_no_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaenc',
            name='no_factura',
            field=models.CharField(max_length=10),
        ),
    ]
