# Generated by Django 3.2.5 on 2021-11-28 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0029_alter_facturaenc_no_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadet',
            name='fecha_detalle',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReporteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('producto', models.CharField(max_length=3)),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encabezado Orden Factura',
                'verbose_name_plural': 'Encabezado Orden Facturas',
                'permissions': [('sup_caja_facturaenc', 'Permisos de Supervisor de Caja Orden Encabezado')],
            },
        ),
    ]
