# Generated by Django 3.2.5 on 2021-11-29 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0030_auto_20211128_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReporteProducto',
        ),
    ]
