# Generated by Django 3.2.9 on 2021-11-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_alter_facturaenc_no_factura'),
        ('ventas', '0031_delete_reporteproducto'),
    ]

    operations = [
    ]
