# Generated by Django 3.2.9 on 2021-11-29 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0033_alter_facturaenc_no_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
