# Generated by Django 3.2.5 on 2021-11-29 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0034_alter_caja_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
