# Generated by Django 3.2.6 on 2021-10-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_alter_proveedor_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='estado_c',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='apellido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cedula',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
