# Generated by Django 3.2.5 on 2021-10-24 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_remove_producto_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedor', '0006_comprasdet_estado_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenComprasEnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_c', models.BooleanField(default=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('sub_total', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encabezado Orden Compra',
                'verbose_name_plural': 'Encabezado de Orden Compras',
            },
        ),
        migrations.CreateModel(
            name='OrdenComprasDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_c', models.BooleanField(default=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.BigIntegerField(default=0)),
                ('precio_prv', models.FloatField(default=0)),
                ('sub_total', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('costo', models.FloatField(default=0)),
                ('estado_compra', models.CharField(default='En proceso', max_length=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.comprasenc')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Orden Compra',
                'verbose_name_plural': 'Detalles orden Compras',
            },
        ),
    ]
