# Generated by Django 3.2.6 on 2021-10-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0006_auto_20211024_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprasdet',
            old_name='estado_c',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='comprasenc',
            old_name='estado_c',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='estado_c',
            new_name='estado',
        ),
    ]
