# Generated by Django 3.2.5 on 2021-10-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0007_ordencomprasdet_ordencomprasenc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencomprasenc',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
