# Generated by Django 3.2.5 on 2021-10-24 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0008_ordencomprasenc_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencomprasdet',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.ordencomprasenc'),
        ),
    ]
