# Generated by Django 3.2.5 on 2021-10-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0008_ordencomprasdet_ordencomprasenc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencomprasenc',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
    ]
