# Generated by Django 3.2.5 on 2021-10-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0009_ordencomprasenc_fecha_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencomprasenc',
            name='proveedor',
        ),
    ]
