# Generated by Django 3.2.5 on 2021-11-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0010_remove_ordencomprasenc_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasenc',
            name='cantidad_cuotas',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cuotas', models.BigIntegerField(default=0)),
                ('monto_mensual', models.FloatField(default=0)),
                ('monto_total_pag', models.FloatField(default=0)),
                ('estado_cuenta', models.CharField(default='Iniciado', max_length=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.comprasenc')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Pago de Proveedor',
                'verbose_name_plural': 'Pago de Proveedores',
            },
        ),
    ]
