# Generated by Django 3.2.5 on 2021-11-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0013_auto_20211120_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasenc',
            name='fecha_fin_timbrado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprasenc',
            name='fecha_ini_timbrado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprasenc',
            name='no_timbrado',
            field=models.IntegerField(default=0),
        ),
    ]
