# Generated by Django 3.2.5 on 2021-11-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0014_auto_20211122_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasdet',
            name='dif_cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
