# Generated by Django 3.2.9 on 2021-11-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0014_auto_20211122_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='fecha_compra',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
