# Generated by Django 3.2.9 on 2021-11-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0015_alter_comprasenc_fecha_compra'),
        ('proveedor', '0015_comprasdet_dif_cantidad'),
    ]

    operations = [
    ]
