# Generated by Django 3.2.9 on 2021-11-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0016_merge_20211124_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='no_factura',
            field=models.CharField(default='0000001', max_length=100),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='no_timbrado',
            field=models.IntegerField(default='00000000'),
        ),
    ]
