# Generated by Django 3.2.9 on 2021-11-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0018_auto_20211124_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='cantidad_cuotas',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='no_timbrado',
            field=models.IntegerField(default=0, max_length=8),
        ),
    ]
