# Generated by Django 3.2.9 on 2021-11-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0019_auto_20211126_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='no_timbrado',
            field=models.CharField(max_length=8),
        ),
    ]
