# Generated by Django 3.2.5 on 2021-08-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=5, unique=True)),
                ('product_name', models.CharField(max_length=5)),
                ('stock_actual', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('unidad_medida', models.CharField(max_length=5)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_caducidad', models.DateTimeField()),
                ('categoria', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
            ],
        ),
    ]
