# Generated by Django 3.2.5 on 2021-08-29 00:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0003_alter_producto_fecha_caducidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='product_id',
        ),
        migrations.AddField(
            model_name='producto',
            name='uc',
            field=models.ForeignKey(default='0001', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='um',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
