# Generated by Django 3.2.5 on 2021-09-06 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20210829_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='stock_actual',
            new_name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_caducidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
    ]
