# Generated by Django 3.2.6 on 2021-10-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20210906_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='cod_def', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado_c',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='existencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.FloatField(default=0),
        ),
    ]
