# Generated by Django 3.2.5 on 2021-10-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_producto_existencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
