# Generated by Django 3.2.6 on 2021-10-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_remove_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fc',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fm',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
