# Generated by Django 3.2.6 on 2021-10-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_auto_20211027_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_venta',
            new_name='precio',
        ),
    ]
