# Generated by Django 3.2.9 on 2021-12-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_notacredito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotaCredito',
        ),
    ]
