# Generated by Django 3.2.9 on 2021-12-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_notacredito_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='descripcion',
            field=models.CharField(default='.', max_length=200),
        ),
    ]
