# Generated by Django 3.2.9 on 2021-12-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_notacredito_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notacredito',
            old_name='iva',
            new_name='gravada',
        ),
        migrations.RemoveField(
            model_name='notacredito',
            name='iva_10',
        ),
    ]
