# Generated by Django 3.2.9 on 2021-12-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_auto_20211206_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='iva',
            field=models.FloatField(default=0),
        ),
    ]
