# Generated by Django 3.2.6 on 2021-08-26 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clientes', '0002_alter_cliente_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='clienteId',
        ),
        migrations.AddField(
            model_name='cliente',
            name='uc',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='um',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
    ]
