# Generated by Django 3.2.7 on 2021-10-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0007_alter_cliente_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_c',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
