# Generated by Django 3.2.6 on 2021-10-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_auto_20211004_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fc',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fm',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
