# Generated by Django 3.2.6 on 2021-10-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20211027_0305'),
        ('Clientes', '0009_auto_20211024_2345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
